export const restaurantData = [
    {
        id: 1,
        name: "Delicious Bites",
        restaurant_type: "Casual Dining",
        address: "123 Main Street",
        logo_url: "https://example.com/delicious-bites-logo.jpg",
        city: "Cityville",
        description: "A cozy place with a wide variety of tasty dishes.",
        num_menus: 5,
    },
    {
        id: 2,
        name: "Gourmet Fusion",
        restaurant_type: "Fine Dining",
        address: "456 Oak Avenue",
        logo_url: "https://example.com/gourmet-fusion-logo.jpg",
        city: "Metropolis",
        description: "Exquisite flavors and a sophisticated dining experience.",
        num_menus: 8,
    },
    {
        id: 3,
        name: "Spicy Bites",
        restaurant_type: "Fast Food",
        address: "789 Pine Street",
        logo_url: "https://example.com/spicy-bites-logo.jpg",
        city: "Townsville",
        description: "Quick and flavorful options for those on the go.",
        num_menus: 3,
    },
    {
        id: 4,
        name: "Sizzling Grill",
        restaurant_type: "Barbecue",
        address: "789 Oak Lane",
        logo_url: "https://example.com/sizzling-grill-logo.jpg",
        city: "Villageville",
        description: "Mouth-watering barbecue delights in a rustic setting.",
        num_menus: 6,
    },
    {
        id: 5,
        name: "Seafood Haven",
        restaurant_type: "Seafood",
        address: "234 Beach Boulevard",
        logo_url: "https://example.com/seafood-haven-logo.jpg",
        city: "Coastal City",
        description: "Fresh catch of the day served with a seaside view.",
        num_menus: 7,
    },
    {
        id: 6,
        name: "Veggie Delight",
        restaurant_type: "Vegetarian",
        address: "567 Green Avenue",
        logo_url: "https://example.com/veggie-delight-logo.jpg",
        city: "Greenville",
        description: "A haven for vegetarians with a variety of plant-based options.",
        num_menus: 4,
    },
];

