# Generated by Django 4.2.7 on 2023-11-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
