# Generated by Django 4.2.7 on 2023-11-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_menu_restaurant_id_delete_restaurantmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_menus',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
